### ISSUE TITLE
Issue on Windows 10

### ISSUE THREAD

**Issue by SweRavn** [chipmuenk/pyfda#181] opened 2020-09-09 10:32 UTC
Got the following issue when running from anaconda with pip installing pyqt5 and pyfda in an environment:

(pyfda) PS C:\Users\rore\bin> pyfdax
[   INFO] [pyfda.pyfda_rc:191] Using 'DejaVu Sans' font.
[   INFO] [pyfda.libs.tree_builder:261] Parsing config file
        'C:\Users\rore\.pyfda\pyfda.conf' with sections:
                [Common]
                [Input Widgets]
                [Plot Widgets]
                [Filter Designs]
                [Fixpoint Widgets]

[   INFO] [pyfda.libs.tree_builder:269] Found 3 entries in [Common]
[   INFO] [pyfda.libs.tree_builder:292] No valid user directory specified.
[WARNING] [pyfda.libs.pyfda_lib:140] Version number of migen could not be determined.
[   INFO] [pyfda.libs.tree_builder:537] Found 6 classes in [Input Widgets]:
        pyfda.input_widgets.input_specs.Input_Specs
        pyfda.input_widgets.input_coeffs.Input_Coeffs
        pyfda.input_widgets.input_pz.Input_PZ
        pyfda.input_widgets.input_info.Input_Info
        pyfda.input_widgets.input_files.Input_Files
        pyfda.input_widgets.input_fixpoint_specs.Input_Fixpoint_Specs

c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py:41: MatplotlibDeprecationWarning:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  rcParams[key] = pyfda_rc.mpl_rc[key]
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py:41: MatplotlibDeprecationWarning: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
  rcParams[key] = pyfda_rc.mpl_rc[key]
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py:41: MatplotlibDeprecationWarning:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  rcParams[key] = pyfda_rc.mpl_rc[key]
[   INFO] [pyfda.libs.tree_builder:537] Found 6 classes in [Plot Widgets]:
        pyfda.plot_widgets.plot_hf.Plot_Hf
        pyfda.plot_widgets.plot_phi.Plot_Phi
        pyfda.plot_widgets.plot_tau_g.Plot_tau_g
        pyfda.plot_widgets.plot_pz.Plot_PZ
        pyfda.plot_widgets.plot_impz.Plot_Impz
        pyfda.plot_widgets.plot_3d.Plot_3D

[   INFO] [pyfda.libs.tree_builder:537] Found 12 classes in [Filter Designs]:
        pyfda.filter_designs.bessel.Bessel
        pyfda.filter_designs.butter.Butter
        pyfda.filter_designs.cheby1.Cheby1
        pyfda.filter_designs.cheby2.Cheby2
        pyfda.filter_designs.ellip.Ellip
        pyfda.filter_designs.ellip_zero.EllipZeroPhz
        pyfda.filter_designs.equiripple.Equiripple
        pyfda.filter_designs.firwin.Firwin
        pyfda.filter_designs.ma.MA
        pyfda.filter_designs.delay.Delay
        pyfda.filter_designs.manual.Manual_FIR
        pyfda.filter_designs.manual.Manual_IIR

[   INFO] [pyfda.libs.tree_builder:537] Found 2 classes in [Fixpoint Widgets]:
        pyfda.fixpoint_widgets.fir_df.FIR_DF_wdg
        pyfda.fixpoint_widgets.fx_delay.Delay_wdg

[   INFO] [pyfda.input_widgets.input_specs:302] Start filter design using method
        'Equiripple.LPman'
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\numpy\lib\type_check.py:461: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x = _nx.array(x, subok=True, copy=copy)
[   INFO] [pyfda.input_widgets.input_specs:336] Designed filter with order = 10
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\input_widgets\input_pz.py:481: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self.zpk = np.array(fb.fil[0]['zpk'])# this enforces a deep copy
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py:241: MatplotlibDeprecationWarning:
The _init_toolbar method was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Please fully initialize the toolbar in your subclass' __init__; a fully empty _init_toolbar implementation may be kept for compatibility with earlier versions of Matplotlib.
  NavigationToolbar.__init__(self, *args, **kwargs)
c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py:284: MatplotlibDeprecationWarning:
The parent attribute was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use self.canvas.setParent() instead.
  'Zoom full extent', self.parent.plt_full_view)
Traceback (most recent call last):
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rore\AppData\Local\Continuum\anaconda3\envs\pyfda\Scripts\pyfdax.exe\__main__.py", line 7, in <module>
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\pyfdax.py", line 290, in main
    mainw = pyFDA()
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\pyfdax.py", line 134, in __init__
    self._construct_UI()
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\pyfdax.py", line 147, in _construct_UI
    pltTabWidgets = plot_tab_widgets.PlotTabWidgets(self) # plot widgets
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\plot_tab_widgets.py", line 34, in __init__
    self._construct_UI()
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\plot_tab_widgets.py", line 72, in _construct_UI
    inst = wdg_class(self)
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\plot_hf.py", line 49, in __init__
    self._construct_ui()
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\plot_hf.py", line 159, in _construct_ui
    self.mplwidget = MplWidget(self)
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py", line 96, in __init__
    self.mplToolbar = MplToolbar(self.pltCanv, self) # inherits all methods
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py", line 241, in __init__
    NavigationToolbar.__init__(self, *args, **kwargs)
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\matplotlib\backends\backend_qt5.py", line 687, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\matplotlib\backend_bases.py", line 2857, in __init__
    init()
  File "c:\users\rore\appdata\local\continuum\anaconda3\envs\pyfda\lib\site-packages\pyfda\plot_widgets\mpl_widget.py", line 284, in _init_toolbar
    'Zoom full extent', self.parent.plt_full_view)
AttributeError: 'NoneType' object has no attribute 'plt_full_view'
(pyfda) PS C:\Users\rore\bin>

**Comment by chipmuenk** [comment] 2020-09-09 17:03
This is the same issue as #179 - closing. The problem is fixed in the latest develop branch.

**Closed by chipmuenk** 2020-09-09 17:03 UTC
