### ISSUE TITLE
ImportError: No module named 'matplotlib.externals' 

### ISSUE THREAD

**Issue by smithbone** [chipmuenk/pyFDA#95] opened 2017-11-24 04:56 UTC
I'm unable to run pyFDA.  After I tweaked the log file to be in /tmp (see issue #80) I still can't start pyFDA. The full exception is below.  This is a Linux Ubuntu 16.04 LTS system.

rsmith@gatito:~$ pyfdax 
matplotlib  : 2.1.0
numpy       : 1.13.3
pyqt        : 5.6.1
python      : 3.5.2
python_long : 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609]
scipy       : 0.17.0

[   INFO] [root:36] Using logging config file pyfda_log.conf.
UNIX None
/usr/local/lib/python3.5/dist-packages/pyfda/pyfdax.py:55: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/usr/local/bin/pyfdax", line 7, in <module>
    from pyfda.pyfdax import main
  File "/usr/local/lib/python3.5/dist-packages/pyfda/pyfdax.py", line 16, in <module>
    from pyfda import pyfda_rc as rc
  File "/usr/local/lib/python3.5/dist-packages/pyfda/pyfda_rc.py", line 28, in <module>
    from pyfda import qrc_resources # contains all icons
  File "/usr/local/lib/python3.5/dist-packages/pyfda/qrc_resources.py", line 9, in <module>
    from .compat import QtCore
  File "/usr/local/lib/python3.5/dist-packages/pyfda/compat.py", line 16, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

  matplotlib.use("Qt5Agg")
Traceback (most recent call last):
  File "/usr/local/bin/pyfdax", line 7, in <module>
    from pyfda.pyfdax import main
  File "/usr/local/lib/python3.5/dist-packages/pyfda/pyfdax.py", line 69, in <module>
    from pyfda.plot_widgets import plot_tab_widgets
  File "/usr/local/lib/python3.5/dist-packages/pyfda/plot_widgets/plot_tab_widgets.py", line 16, in <module>
    from pyfda.plot_widgets import (plot_hf, plot_phi, plot_pz, plot_tau_g, plot_impz,
  File "/usr/local/lib/python3.5/dist-packages/pyfda/plot_widgets/plot_3d.py", line 23, in <module>
    from mpl_toolkits.mplot3d.axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 4, in <module>
    from matplotlib.externals import six
ImportError: No module named 'matplotlib.externals'

**Comment by chipmuenk** [comment] 2017-11-24 12:39
I haven't had this one and I can't reproduce the error in my environment - something is broken in my anaconda env handling. 

Could it be that your error is related to having two different matplotlib versions installed on top of each other as described in  https://github.com/matplotlib/matplotlib/issues/5633/ ?

I'm working on the install issue #80 ...

**Comment by smithbone** [comment] 2017-11-25 23:02
Thanks for the pointer to the other issue, it was very helpful. It seems that if I use pip and allow it to upgrade then pip will install a later version of matplotlib than what is provided by Ubuntu and causes the above problems. 
I was able to work around the problems by removing the ubuntu provided version but I had to use the 'purge' option to remove any left over configuration files as well.

pyFDA now loads however I still receive the following console message about .use() being ineffective:

rsmith@gatito:~$ pyfdax
matplotlib  : 2.1.0
numpy       : 1.13.3
pyqt        : 5.6.1
python      : 3.5.2
python_long : 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609]
scipy       : 0.17.0

[   INFO] [root:36] Using logging config file pyfda_log.conf.
UNIX None
/usr/local/lib/python3.5/dist-packages/pyfda/pyfdax.py:55: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/usr/local/bin/pyfdax", line 7, in <module>
    from pyfda.pyfdax import main
  File "/usr/local/lib/python3.5/dist-packages/pyfda/pyfdax.py", line 16, in <module>
    from pyfda import pyfda_rc as rc
  File "/usr/local/lib/python3.5/dist-packages/pyfda/pyfda_rc.py", line 28, in <module>
    from pyfda import qrc_resources # contains all icons
  File "/usr/local/lib/python3.5/dist-packages/pyfda/qrc_resources.py", line 9, in <module>
    from .compat import QtCore
  File "/usr/local/lib/python3.5/dist-packages/pyfda/compat.py", line 16, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use("Qt5Agg")
[   INFO] [pyfda.filter_tree_builder:228] 9 entries found in filter list!

[   INFO] [pyfda.filter_tree_builder:329] Imported successfully the following 10 filter classes:
        cheby1.Cheby1
        equiripple.Equiripple
        firwin.Firwin
        cheby2.Cheby2
        ellip.Ellip
        butter.Butter
        bessel.Bessel
        ma.MA
        manual.Manual_IIR
        manual.Manual_FIR

/usr/local/lib/python3.5/dist-packages/matplotlib/font_manager.py:1316: UserWarning: findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))

**Comment by chipmuenk** [comment] 2017-11-26 11:48
Thanks a lot for your pointer - I got the message about .use() as well but couldn't track down the cause, because I don't get the detailed trackback. I only got a message "warnings.warn(_use_error_msg)" that didn't help me. How did you turn on the detailled messages?

Anyway, I reordered the imports until the warning disappeared (checked in in branch 'set_directories').

**Comment by chipmuenk** [comment] 2017-11-26 16:45
The latest PR & merge to master should fix #80 as well - please test and give me feedback!

**Comment by smithbone** [comment] 2017-11-26 17:24
> didn't help me. How did you turn on the detailled messages?
I didn't do anything specific to turn them on so sorry I can't be much help there.  

I can confirm that master now takes care of both issues.  I don't have to tweak the log file location and I no longer receive the warning. Thanks for the fix.

I suspect that any Ubuntu 16.04 LTS user will run into the 'matplotlib.externals' problem if they allow pip to upgrade the matplotlib install.  It's probably worth some sort of note to watch for that in the install document otherwise you may get more duplicate reports.

**Comment by smithbone** [comment] 2017-11-26 17:24
ooops.  Didn't mean to close.  I'll let you close.

**Comment by chipmuenk** [comment] 2017-11-27 06:59
That's fine - you could have closed the issue yourself. And thanks for the feedback!

**Closed by chipmuenk** 2017-11-27 06:59 UTC
