### ISSUE TITLE
Please consider reducing module dependencies

### ISSUE THREAD

**Issue by vuki** [chipmuenk/pyfda#156] opened 2019-10-30 09:10 UTC
I'm trying to keep my python installation clean, without unneeded modules. Unfortunately, pyfda installs an insane number of modules. The result of my attempt to install pyfda:

`Successfully installed alabaster-0.7.12 babel-2.7.0 imagesize-1.1.0 migen-0.9.1 pyfda-0.2 snowballstemmer-2.0.0 sphinx-2.2.0 sphinx-rtd-theme-0.4.3 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3`

As far as I know, from all these modules, only migen is actually needed for pyfda to work correctly. The rest is a result of including the documentation building system. This is completely not needed for the end user. I think that the end user does not even get the created documentation,. Therefore, all these modules are not needed and they pollute the python environment,

Please consider removing these modules from the end user installation.

**Comment by chipmuenk** [comment] 2019-10-30 09:39
You're right, this shouldn't be. 

My pyfda `setup.py` controlling the packaging for pip / PyPI just contains the lines

    install_requires = [
        'numpy',
        'scipy',
        'matplotlib',
        'pyqt5',
        'docutils',
        'migen'
        ],

which should be ok.

The `meta.yaml` determining conda packaging of pyfda contains

    requirements:
      host:
        - docutils
        - matplotlib
        - migen
        - numpy
        - pip
        - python
        - scipy
        - pyqt5
      run:
        - docutils
        - matplotlib
        - migen
        - numpy
        - python
        - scipy
        - pyqt5

which also looks good to me.

I think the problem is in the `setup.py` for migen which contains the line

    requirements = ["sphinx", "sphinx_rtd_theme", "colorama"]

I have forked the migen project to create PyPI and conda packages (which the migen team doesn't do) so that pyfda can be installed easily. I guess you could call that a collateral damage ... I'll talk to the migen team and submit a PR but this might take a little.

**Comment by chipmuenk** [comment] 2019-11-03 18:34
Fixed in release 0.9.2 of the migen module (available on PyPI and conda channel `Chipmuenk`), the only requirement now is `colorama`. When installing pyfda the latest migen release is used.

**Closed by chipmuenk** 2019-11-03 18:34 UTC
