### ISSUE TITLE
No attribute plt_full_view with Matplotlib 3.3

### ISSUE THREAD

**Issue by nlbutts** [chipmuenk/pyfda#179] opened 2020-08-17 14:48 UTC
I receive the following error message:
Traceback (most recent call last):
  File "/home/nlbutts/venv/bin/pyfdax", line 8, in <module>
    sys.exit(main())
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/pyfdax.py", line 290, in main
    mainw = pyFDA()
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/pyfdax.py", line 134, in __init__
    self._construct_UI()
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/pyfdax.py", line 147, in _construct_UI
    pltTabWidgets = plot_tab_widgets.PlotTabWidgets(self) # plot widgets
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/plot_tab_widgets.py", line 34, in __init__
    self._construct_UI()
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/plot_tab_widgets.py", line 72, in _construct_UI
    inst = wdg_class(self)
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/plot_hf.py", line 49, in __init__
    self._construct_ui()
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/plot_hf.py", line 159, in _construct_ui
    self.mplwidget = MplWidget(self)
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/mpl_widget.py", line 96, in __init__
    self.mplToolbar = MplToolbar(self.pltCanv, self) # inherits all methods
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/mpl_widget.py", line 241, in __init__
    NavigationToolbar.__init__(self, *args, **kwargs)
  File "/home/nlbutts/venv/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 687, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/nlbutts/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2853, in __init__
    init()
  File "/home/nlbutts/venv/lib/python3.6/site-packages/pyfda/plot_widgets/mpl_widget.py", line 284, in _init_toolbar
    'Zoom full extent', self.parent.plt_full_view)
AttributeError: 'NoneType' object has no attribute 'plt_full_view'

Below is my environment:
colorama==0.4.3
cycler==0.10.0
docutils==0.16
kiwisolver==1.2.0
matplotlib==3.3.0
migen==0.9.2
numpy==1.19.1
Pillow==7.2.0
pkg-resources==0.0.0
pyfda==0.3.1
pyparsing==2.4.7
PyQt5==5.15.0
PyQt5-sip==12.8.0
python-dateutil==2.8.1
scipy==1.5.2
six==1.15.0
speedtest-cli==2.1.2

**Comment by chipmuenk** [comment] 2020-08-19 09:23
It seems Matplotlib 3.3 introduced some incompatible  API changes to the Navigation Toolbar (see #178). I'll check that when I'm back from vacation, please try to revert to Matplotlib 3.2 in the meantime.

**Comment by chipmuenk** [comment] 2020-09-09 17:05
The problem is fixed in the develop branch, I'm preparing a proper release.

**Closed** 2020-09-29 13:34 UTC
